# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
baseURL = "https://zfleeman.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

enableGitInfo = false

buildDrafts = false
buildFuture = false

#Â googleAnalytics = "G-XXXXXXXXX"

[imaging]
  quality = 100
  resampleFilter = 'Lanczos'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
